RANDOMWALK-42 Init project and add token exchange grant type support
ru-random-walk/auth-service pull request #1
Opened 2024-09-11 15:10 UTC by kryakobess

Review

2024-09-27 09:57 UTC, maksmolchdmitr requested changes

2024-09-27 09:58 UTC, kryakobess commented on src/main/java/ru/random/walk/authservice/config/security/jwt/JwtAuthFilter.java
> +//@Service
Пока удалю, в будущем для админки будет использоваться

2024-09-27 09:59 UTC, kryakobess commented on src/main/java/ru/random/walk/authservice/config/security/jwt/JwtAuthFilter.java
> +            //SecurityContextHolder.getContext().setAuthentication(jwtService.parseToken(jwt));
Это фильтр на авторизацию, тут нужно будет парсить токен, чтобы войти пользователю. Сейчас админки нет

2024-09-27 16:05 UTC, maksmolchdmitr requested changes

2024-09-27 16:05 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/authservice/service/mapper/ClientMapper.java
> +}
Удалить?

2024-09-27 16:05 UTC, maksmolchdmitr commented on src/main/resources/application.yaml
> +    kQIDAQAB
В env-vars запихнуть

2024-09-27 16:08 UTC, kryakobess commented on src/main/java/ru/random/walk/authservice/controller/OAuth2Controller.java
> +    @GetMapping("/.well-known/openid-configuration")
Да, это стандарт в оауфе

2024-09-27 16:11 UTC, kryakobess commented on src/main/resources/application.yaml
> +    kQIDAQAB
Это локальные, новые в секреты создам

2024-09-27 17:28 UTC, kryakobess commented on src/main/java/ru/random/walk/authservice/config/security/jwt/JwtProperties.java
> +}
Classes annotated with '@Configuration' could be implicitly subclassed and must not be final

2024-09-27 17:59 UTC, kryakobess commented on src/main/java/ru/random/walk/authservice/config/AuthServiceProperties.java
> +}
Classes annotated with '@configuration' could be implicitly subclassed and must not be final

2024-09-28 12:10 UTC, maksmolchdmitr requested changes

2024-09-28 12:10 UTC, maksmolchdmitr commented on src/main/java/ru/random/walk/authservice/service/impl/JwtServiceImpl.java
> +                .setExpiration(Date.from(LocalDateTime.now().plusMinutes(jwtProperties.getExpireTimeInMinutes()).atZone(ZoneId.systemDefault()).toInstant()))
Было бы клёво разбивать одну строку на несколько:
![image](https://github.com/user-attachments/assets/e3387464-b1a7-4b0e-bf53-a9b092bfe53f)
Для повышения читаемости кода

2024-09-28 12:10 UTC, maksmolchdmitr commented on src/main/resources/application-local.yaml
> +    kQIDAQAB
Это нужно в отдельные env vars зафигачить

2024-09-28 12:46 UTC, maksmolchdmitr approved these changes

2024-09-28 12:49 UTC, merged